# Asset registry — edit this file to add/update stocks, DPS rates, and aliases.
# app.py imports everything from here; no other changes needed.

# The fiscal year from which all Rate values were sourced.
# UPDATE this string whenever you refresh any Rate value.
_DPS_AS_OF = "FY 2024"

# Per-holding caveats shown as warnings throughout the app.
# Add an entry here whenever a Rate requires user attention.
DPS_NOTES = {
    "DBS": (
        "Rate updated to S$2.22 (FY 2024 ordinary only). "
        "DBS also pays a recurring S$0.50/share special capital return — "
        "add it back to Rate if you wish to include it in income projections."
    ),
    "HPH TRUST USD": (
        "Distributions are paid in USD, not SGD. "
        "Rate 0.02 is used here as SGD — cross-check against the prevailing USD/SGD rate "
        "and adjust Rate to the SGD-equivalent for accurate income figures."
    ),
    "KEPPEL": (
        "Keppel Corp completed a major restructuring in 2023. "
        "Verify Rate against the latest post-restructuring annual report DPS."
    ),
    "MAPLETREE LOG TR": (
        "Mapletree Logistics has been reducing DPU in recent quarters due to rising costs. "
        "Verify Rate against the latest declared DPU before relying on income projections."
    ),
}

# Maps PDF name patterns (uppercased) to a canonical MASTER_INTEL key.
# Keys must resolve case-insensitively to a MASTER_INTEL entry.
ALIAS_MAP = {
    "OCBC BANK": ["OVERSEA-CHINESE", "OVERSEA CHINESE"],
    "UOB": ["UNITED OVERSEAS", "UOB"],
    "DBS": ["DBS GROUP", "DBS"],
    "SINGTEL": ["SINGAPORE TELECOM", "SINGTEL"],
    "MAPLETREE LOG TR": ["MAPLETREE LOGISTICS", "MAPLETREE LOG"],
    "ST ENGINEERING": ["SINGAPORE TECHNOLOGIES", "ST ENGG"],
    "CITYDEV": ["CITY DEVELOPMENTS"],
    "COMFORTDELGRO": ["COMFORT DELGRO"],
}

# Central stock registry. Maps display name → {Rate, PB, Ticker, Sector}.
# Rate = DPS in SGD, PB = price-to-book, Ticker = Yahoo Finance SGX code (no .SI suffix).
# To add a new stock, append an entry here; app.py will pick it up automatically.
MASTER_INTEL = {
    "EliteUKREIT SGD": {"Rate": 0.00, "PB": 0.00, "Ticker": "MENU", "Sector": "-"},
    "MDR Limited R": {"Rate": 0.00, "PB": 0.00, "Ticker": "NXNR", "Sector": "-"},
    "MDR Limited R1": {"Rate": 0.00, "PB": 0.00, "Ticker": "V2OR", "Sector": "-"},
    "RichCapital": {"Rate": 0.00, "PB": 0.00, "Ticker": "1U8", "Sector": "-"},
    "Abundance Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "541", "Sector": "Basic Materials"},
    "Alita Resources": {"Rate": 0.00, "PB": 0.00, "Ticker": "40F", "Sector": "Basic Materials"},
    "Anchun Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "BTX", "Sector": "Basic Materials"},
    "AnnAik": {"Rate": 0.00, "PB": 0.00, "Ticker": "A52", "Sector": "Basic Materials"},
    "Ascent Bridge": {"Rate": 0.00, "PB": 0.00, "Ticker": "AWG", "Sector": "Basic Materials"},
    "Asia Enterprises": {"Rate": 0.00, "PB": 0.00, "Ticker": "A55", "Sector": "Basic Materials"},
    "AsiaPhos": {"Rate": 0.00, "PB": 0.00, "Ticker": "5WV", "Sector": "Basic Materials"},
    "BRC Asia": {"Rate": 0.00, "PB": 0.00, "Ticker": "BEC", "Sector": "Basic Materials"},
    "CNMC Goldmine": {"Rate": 0.00, "PB": 0.00, "Ticker": "5TP", "Sector": "Basic Materials"},
    "Chemical Ind": {"Rate": 0.00, "PB": 0.00, "Ticker": "C05", "Sector": "Basic Materials"},
    "ChinaSunsine": {"Rate": 0.00, "PB": 0.00, "Ticker": "QES", "Sector": "Basic Materials"},
    "EnGro": {"Rate": 0.00, "PB": 0.00, "Ticker": "S44", "Sector": "Basic Materials"},
    "FortressMinerals": {"Rate": 0.00, "PB": 0.00, "Ticker": "OAJ", "Sector": "Basic Materials"},
    "GCCP": {"Rate": 0.00, "PB": 0.00, "Ticker": "41T", "Sector": "Basic Materials"},
    "HG Metal": {"Rate": 0.00, "PB": 0.00, "Ticker": "BTG", "Sector": "Basic Materials"},
    "Halcyon Agri": {"Rate": 0.00, "PB": 0.00, "Ticker": "5VJ", "Sector": "Basic Materials"},
    "Infinity Dev": {"Rate": 0.00, "PB": 0.00, "Ticker": "ZBA", "Sector": "Basic Materials"},
    "Intl Cement": {"Rate": 0.00, "PB": 0.00, "Ticker": "KUO", "Sector": "Basic Materials"},
    "Jawala": {"Rate": 0.00, "PB": 0.00, "Ticker": "1J7", "Sector": "Basic Materials"},
    "Jiutian Chemical": {"Rate": 0.00, "PB": 0.00, "Ticker": "C8R", "Sector": "Basic Materials"},
    "Kep Infra Tr": {"Rate": 0.04, "PB": 2.10, "Ticker": "A7RU", "Sector": "Basic Materials"},
    "LHT": {"Rate": 0.00, "PB": 0.00, "Ticker": "BEI", "Sector": "Basic Materials"},
    "Le Tree Holdings": {"Rate": 0.00, "PB": 0.00, "Ticker": "E6R", "Sector": "Basic Materials"},
    "Lion Asiapac": {"Rate": 0.00, "PB": 0.00, "Ticker": "BAZ", "Sector": "Basic Materials"},
    "Luxking": {"Rate": 0.00, "PB": 0.00, "Ticker": "BKK", "Sector": "Basic Materials"},
    "MSC": {"Rate": 0.00, "PB": 0.00, "Ticker": "NPW", "Sector": "Basic Materials"},
    "MegaChem": {"Rate": 0.00, "PB": 0.00, "Ticker": "5DS", "Sector": "Basic Materials"},
    "NSL": {"Rate": 0.00, "PB": 0.00, "Ticker": "N02", "Sector": "Basic Materials"},
    "Nanyang NewDev": {"Rate": 0.00, "PB": 0.00, "Ticker": "M15", "Sector": "Basic Materials"},
    "New Wave": {"Rate": 0.00, "PB": 0.00, "Ticker": "5FX", "Sector": "Basic Materials"},
    "Nippecraft": {"Rate": 0.00, "PB": 0.00, "Ticker": "N32", "Sector": "Basic Materials"},
    "PanUnited": {"Rate": 0.00, "PB": 0.00, "Ticker": "P52", "Sector": "Basic Materials"},
    "Samurai 2K": {"Rate": 0.00, "PB": 0.00, "Ticker": "Y8E", "Sector": "Basic Materials"},
    "Sen Yue": {"Rate": 0.00, "PB": 0.00, "Ticker": "5BS", "Sector": "Basic Materials"},
    "Shen Yao": {"Rate": 0.00, "PB": 0.00, "Ticker": "A78", "Sector": "Basic Materials"},
    "Soon Lian": {"Rate": 0.00, "PB": 0.00, "Ticker": "5MD", "Sector": "Basic Materials"},
    "SouthernAlliance": {"Rate": 0.00, "PB": 0.00, "Ticker": "QNS", "Sector": "Basic Materials"},
    "Sri Trang Agro": {"Rate": 0.00, "PB": 0.00, "Ticker": "NC2", "Sector": "Basic Materials"},
    "Sri Trang Gloves": {"Rate": 0.00, "PB": 0.00, "Ticker": "STG", "Sector": "Basic Materials"},
    "Straits Trading": {"Rate": 0.00, "PB": 0.00, "Ticker": "S20", "Sector": "Basic Materials"},
    "Wilton Resources": {"Rate": 0.00, "PB": 0.00, "Ticker": "5F7", "Sector": "Basic Materials"},
    "Asian Pay Tv Tr": {"Rate": 0.01, "PB": 0.45, "Ticker": "S7OU", "Sector": "Communication Services"},
    "BACUI TECH": {"Rate": 0.00, "PB": 0.00, "Ticker": "YYB", "Sector": "Communication Services"},
    "Captii": {"Rate": 0.00, "PB": 0.00, "Ticker": "AWV", "Sector": "Communication Services"},
    "Digilife Tech": {"Rate": 0.00, "PB": 0.00, "Ticker": "BAI", "Sector": "Communication Services"},
    "GHY Culture": {"Rate": 0.00, "PB": 0.00, "Ticker": "XJB", "Sector": "Communication Services"},
    "Goodwill": {"Rate": 0.00, "PB": 0.00, "Ticker": "GEH", "Sector": "Communication Services"},
    "MM2 Asia": {"Rate": 0.00, "PB": 0.00, "Ticker": "1B0", "Sector": "Communication Services"},
    "NetLink NBN Tr": {"Rate": 0.05, "PB": 1.35, "Ticker": "CJLU", "Sector": "Communication Services"},
    "NoonTalk Media": {"Rate": 0.00, "PB": 0.00, "Ticker": "SEJ", "Sector": "Communication Services"},
    "Shopper360": {"Rate": 0.00, "PB": 0.00, "Ticker": "1F0", "Sector": "Communication Services"},
    "Singtel": {"Rate": 0.16, "PB": 1.32, "Ticker": "Z74", "Sector": "Communication Services"},
    "Singtel 10": {"Rate": 0.16, "PB": 1.32, "Ticker": "Z77", "Sector": "Communication Services"},
    "Spackman Entmt": {"Rate": 0.00, "PB": 0.00, "Ticker": "9VW", "Sector": "Communication Services"},
    "StarHub": {"Rate": 0.05, "PB": 2.80, "Ticker": "CC3", "Sector": "Communication Services"},
    "TeleChoice Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "T41", "Sector": "Communication Services"},
    "The Place Hldg": {"Rate": 0.00, "PB": 0.00, "Ticker": "E27", "Sector": "Communication Services"},
    "UnUsUaL": {"Rate": 0.00, "PB": 0.00, "Ticker": "1D1", "Sector": "Communication Services"},
    "Vividthree": {"Rate": 0.00, "PB": 0.00, "Ticker": "OMK", "Sector": "Communication Services"},
    "WinkingStudios": {"Rate": 0.00, "PB": 0.00, "Ticker": "WKS", "Sector": "Communication Services"},
    "ABR": {"Rate": 0.00, "PB": 0.00, "Ticker": "533", "Sector": "Consumer Cyclical"},
    "AF Global": {"Rate": 0.00, "PB": 0.00, "Ticker": "L38", "Sector": "Consumer Cyclical"},
    "AP Strategic": {"Rate": 0.00, "PB": 0.00, "Ticker": "5RA", "Sector": "Consumer Cyclical"},
    "Acma": {"Rate": 0.00, "PB": 0.00, "Ticker": "AYV", "Sector": "Consumer Cyclical"},
    "Aspial Corp": {"Rate": 0.00, "PB": 0.00, "Ticker": "A30", "Sector": "Consumer Cyclical"},
    "Aspial Lifestyle": {"Rate": 0.00, "PB": 0.00, "Ticker": "5UF", "Sector": "Consumer Cyclical"},
    "Autagco": {"Rate": 0.00, "PB": 0.00, "Ticker": "1D3", "Sector": "Consumer Cyclical"},
    "Banyan Tree": {"Rate": 0.00, "PB": 0.00, "Ticker": "B58", "Sector": "Consumer Cyclical"},
    "Bonvests": {"Rate": 0.00, "PB": 0.00, "Ticker": "B28", "Sector": "Consumer Cyclical"},
    "Bromat": {"Rate": 0.00, "PB": 0.00, "Ticker": "9I7", "Sector": "Consumer Cyclical"},
    "Casa": {"Rate": 0.00, "PB": 0.00, "Ticker": "C04", "Sector": "Consumer Cyclical"},
    "Centurion": {"Rate": 0.00, "PB": 0.00, "Ticker": "OU8", "Sector": "Consumer Cyclical"},
    "China EnvRes": {"Rate": 0.00, "PB": 0.00, "Ticker": "UIX", "Sector": "Consumer Cyclical"},
    "Combine Will": {"Rate": 0.00, "PB": 0.00, "Ticker": "N0Z", "Sector": "Consumer Cyclical"},
    "Cortina": {"Rate": 0.00, "PB": 0.00, "Ticker": "C41", "Sector": "Consumer Cyclical"},
    "Datapulse Tech": {"Rate": 0.00, "PB": 0.00, "Ticker": "BKW", "Sector": "Consumer Cyclical"},
    "Duty Free Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "5SO", "Sector": "Consumer Cyclical"},
    "EuroSports Gbl": {"Rate": 0.00, "PB": 0.00, "Ticker": "5G1", "Sector": "Consumer Cyclical"},
    "FJ Benjamin": {"Rate": 0.00, "PB": 0.00, "Ticker": "F10", "Sector": "Consumer Cyclical"},
    "FoodInnovators": {"Rate": 0.00, "PB": 0.00, "Ticker": "KYB", "Sector": "Consumer Cyclical"},
    "Fuxing China": {"Rate": 0.00, "PB": 0.00, "Ticker": "AWK", "Sector": "Consumer Cyclical"},
    "Genting Sing": {"Rate": 0.00, "PB": 0.00, "Ticker": "G13", "Sector": "Consumer Cyclical"},
    "Grand Banks": {"Rate": 0.00, "PB": 0.00, "Ticker": "G50", "Sector": "Consumer Cyclical"},
    "H2G Green": {"Rate": 0.00, "PB": 0.00, "Ticker": "5AI", "Sector": "Consumer Cyclical"},
    "HL Global Ent": {"Rate": 0.00, "PB": 0.00, "Ticker": "AVX", "Sector": "Consumer Cyclical"},
    "HPL": {"Rate": 0.00, "PB": 0.00, "Ticker": "H15", "Sector": "Consumer Cyclical"},
    "HS Optimus": {"Rate": 0.00, "PB": 0.00, "Ticker": "504", "Sector": "Consumer Cyclical"},
    "Heeton": {"Rate": 0.00, "PB": 0.00, "Ticker": "5DP", "Sector": "Consumer Cyclical"},
    "Helens": {"Rate": 0.00, "PB": 0.00, "Ticker": "HLS", "Sector": "Consumer Cyclical"},
    "Hiap Hoe": {"Rate": 0.00, "PB": 0.00, "Ticker": "5JK", "Sector": "Consumer Cyclical"},
    "Hong Leong Asia": {"Rate": 0.00, "PB": 0.00, "Ticker": "H22", "Sector": "Consumer Cyclical"},
    "Hotel Grand": {"Rate": 0.00, "PB": 0.00, "Ticker": "H18", "Sector": "Consumer Cyclical"},
    "Hotel Royal": {"Rate": 0.00, "PB": 0.00, "Ticker": "H12", "Sector": "Consumer Cyclical"},
    "Incredible": {"Rate": 0.00, "PB": 0.00, "Ticker": "RDR", "Sector": "Consumer Cyclical"},
    "Japan Foods": {"Rate": 0.00, "PB": 0.00, "Ticker": "5OI", "Sector": "Consumer Cyclical"},
    "Jumbo": {"Rate": 0.00, "PB": 0.00, "Ticker": "42R", "Sector": "Consumer Cyclical"},
    "KTMG": {"Rate": 0.00, "PB": 0.00, "Ticker": "XCF", "Sector": "Consumer Cyclical"},
    "Katrina": {"Rate": 0.00, "PB": 0.00, "Ticker": "1A0", "Sector": "Consumer Cyclical"},
    "Kimly": {"Rate": 0.02, "PB": 1.45, "Ticker": "1D0", "Sector": "Consumer Cyclical"},
    "Koda": {"Rate": 0.00, "PB": 0.00, "Ticker": "BJZ", "Sector": "Consumer Cyclical"},
    "LY Corp": {"Rate": 0.00, "PB": 0.00, "Ticker": "1H8", "Sector": "Consumer Cyclical"},
    "Lorenzo Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "5IE", "Sector": "Consumer Cyclical"},
    "MSMIntl": {"Rate": 0.00, "PB": 0.00, "Ticker": "51O", "Sector": "Consumer Cyclical"},
    "Mary Chia": {"Rate": 0.00, "PB": 0.00, "Ticker": "5OX", "Sector": "Consumer Cyclical"},
    "MeGroup": {"Rate": 0.00, "PB": 0.00, "Ticker": "SJY", "Sector": "Consumer Cyclical"},
    "Metro": {"Rate": 0.00, "PB": 0.00, "Ticker": "M01", "Sector": "Consumer Cyclical"},
    "MoneyMax Fin": {"Rate": 0.00, "PB": 0.00, "Ticker": "5WJ", "Sector": "Consumer Cyclical"},
    "NIO Inc. USD OV": {"Rate": 0.00, "PB": 0.00, "Ticker": "NIO", "Sector": "Consumer Cyclical"},
    "New Toyo": {"Rate": 0.00, "PB": 0.00, "Ticker": "N08", "Sector": "Consumer Cyclical"},
    "Noel Gifts Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "543", "Sector": "Consumer Cyclical"},
    "OCTOPUS": {"Rate": 0.00, "PB": 0.00, "Ticker": "43A", "Sector": "Consumer Cyclical"},
    "Old Chang Kee": {"Rate": 0.00, "PB": 0.00, "Ticker": "5ML", "Sector": "Consumer Cyclical"},
    "Ossia Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "O08", "Sector": "Consumer Cyclical"},
    "PSC Corporation": {"Rate": 0.00, "PB": 0.00, "Ticker": "DM0", "Sector": "Consumer Cyclical"},
    "Parkson Retail": {"Rate": 0.00, "PB": 0.00, "Ticker": "O9E", "Sector": "Consumer Cyclical"},
    "Pavillon": {"Rate": 0.00, "PB": 0.00, "Ticker": "596", "Sector": "Consumer Cyclical"},
    "Polaris": {"Rate": 0.00, "PB": 0.00, "Ticker": "5BI", "Sector": "Consumer Cyclical"},
    "ProsperCap": {"Rate": 0.00, "PB": 0.00, "Ticker": "PPC", "Sector": "Consumer Cyclical"},
    "ProsperaGlobal": {"Rate": 0.00, "PB": 0.00, "Ticker": "5HH", "Sector": "Consumer Cyclical"},
    "Qian Hu": {"Rate": 0.00, "PB": 0.00, "Ticker": "BCV", "Sector": "Consumer Cyclical"},
    "SDAI": {"Rate": 0.00, "PB": 0.00, "Ticker": "5TI", "Sector": "Consumer Cyclical"},
    "ST Group Food": {"Rate": 0.00, "PB": 0.00, "Ticker": "DRX", "Sector": "Consumer Cyclical"},
    "SUTL Enterprise": {"Rate": 0.00, "PB": 0.00, "Ticker": "BHU", "Sector": "Consumer Cyclical"},
    "Sakae": {"Rate": 0.00, "PB": 0.00, "Ticker": "5DO", "Sector": "Consumer Cyclical"},
    "Shangri-La HKD": {"Rate": 0.00, "PB": 0.00, "Ticker": "S07", "Sector": "Consumer Cyclical"},
    "Sim Leisure": {"Rate": 0.00, "PB": 0.00, "Ticker": "URR", "Sector": "Consumer Cyclical"},
    "SingaporeKitchen": {"Rate": 0.00, "PB": 0.00, "Ticker": "5WG", "Sector": "Consumer Cyclical"},
    "Sitra": {"Rate": 0.00, "PB": 0.00, "Ticker": "5LE", "Sector": "Consumer Cyclical"},
    "Soup Holdings": {"Rate": 0.00, "PB": 0.00, "Ticker": "5KI", "Sector": "Consumer Cyclical"},
    "Southern Pkg": {"Rate": 0.00, "PB": 0.00, "Ticker": "BQP", "Sector": "Consumer Cyclical"},
    "Stamford Land": {"Rate": 0.00, "PB": 0.00, "Ticker": "H07", "Sector": "Consumer Cyclical"},
    "Stamford Tyres": {"Rate": 0.00, "PB": 0.00, "Ticker": "S29", "Sector": "Consumer Cyclical"},
    "Straco": {"Rate": 0.00, "PB": 0.00, "Ticker": "S85", "Sector": "Consumer Cyclical"},
    "TC Auto": {"Rate": 0.00, "PB": 0.00, "Ticker": "VI2", "Sector": "Consumer Cyclical"},
    "TCIL HK$": {"Rate": 0.00, "PB": 0.00, "Ticker": "T15", "Sector": "Consumer Cyclical"},
    "TSH": {"Rate": 0.00, "PB": 0.00, "Ticker": "KUH", "Sector": "Consumer Cyclical"},
    "Taka Jewellery": {"Rate": 0.00, "PB": 0.00, "Ticker": "42L", "Sector": "Consumer Cyclical"},
    "Tat Seng Pkg": {"Rate": 0.00, "PB": 0.00, "Ticker": "T12", "Sector": "Consumer Cyclical"},
    "Thakral": {"Rate": 0.00, "PB": 0.00, "Ticker": "AWI", "Sector": "Consumer Cyclical"},
    "TheHourGlass": {"Rate": 0.00, "PB": 0.00, "Ticker": "AGS", "Sector": "Consumer Cyclical"},
    "Travelite": {"Rate": 0.00, "PB": 0.00, "Ticker": "BCZ", "Sector": "Consumer Cyclical"},
    "Tung Lok Rest": {"Rate": 0.00, "PB": 0.00, "Ticker": "540", "Sector": "Consumer Cyclical"},
    "Union Gas": {"Rate": 0.00, "PB": 0.00, "Ticker": "1F2", "Sector": "Consumer Cyclical"},
    "VICOM Ltd": {"Rate": 0.00, "PB": 0.00, "Ticker": "WJP", "Sector": "Consumer Cyclical"},
    "ValueMax": {"Rate": 0.00, "PB": 0.00, "Ticker": "T6I", "Sector": "Consumer Cyclical"},
    "Vins Holdings": {"Rate": 0.00, "PB": 0.00, "Ticker": "VIN", "Sector": "Consumer Cyclical"},
    "Y Ventures": {"Rate": 0.00, "PB": 0.00, "Ticker": "1F1", "Sector": "Consumer Cyclical"},
    "YHI Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "BPF", "Sector": "Consumer Cyclical"},
    "YKGI": {"Rate": 0.00, "PB": 0.00, "Ticker": "YK9", "Sector": "Consumer Cyclical"},
    "Zhongmin Baihui": {"Rate": 0.00, "PB": 0.00, "Ticker": "5SR", "Sector": "Consumer Cyclical"},
    "Bumitama Agri": {"Rate": 0.00, "PB": 0.00, "Ticker": "P8Z", "Sector": "Consumer Defensive"},
    "Camsing Hc": {"Rate": 0.00, "PB": 0.00, "Ticker": "BAC", "Sector": "Consumer Defensive"},
    "China Fishery": {"Rate": 0.00, "PB": 0.00, "Ticker": "B0Z", "Sector": "Consumer Defensive"},
    "China Mining": {"Rate": 0.00, "PB": 0.00, "Ticker": "BHD", "Sector": "Consumer Defensive"},
    "ChinaKangdaFood": {"Rate": 0.00, "PB": 0.00, "Ticker": "P74", "Sector": "Consumer Defensive"},
    "DFIRG USD": {"Rate": 0.00, "PB": 0.00, "Ticker": "D01", "Sector": "Consumer Defensive"},
    "Del Monte Pac": {"Rate": 0.00, "PB": 0.00, "Ticker": "D03", "Sector": "Consumer Defensive"},
    "Delfi": {"Rate": 0.00, "PB": 0.00, "Ticker": "P34", "Sector": "Consumer Defensive"},
    "Edition": {"Rate": 0.00, "PB": 0.00, "Ticker": "5HG", "Sector": "Consumer Defensive"},
    "Emperador Inc.": {"Rate": 0.00, "PB": 0.00, "Ticker": "EMI", "Sector": "Consumer Defensive"},
    "Envictus": {"Rate": 0.00, "PB": 0.00, "Ticker": "BQD", "Sector": "Consumer Defensive"},
    "F & N": {"Rate": 0.00, "PB": 0.00, "Ticker": "F99", "Sector": "Consumer Defensive"},
    "First Resources": {"Rate": 0.00, "PB": 0.00, "Ticker": "EB5", "Sector": "Consumer Defensive"},
    "Food Empire": {"Rate": 0.00, "PB": 0.00, "Ticker": "F03", "Sector": "Consumer Defensive"},
    "Golden Agri-Res": {"Rate": 0.00, "PB": 0.00, "Ticker": "E5H", "Sector": "Consumer Defensive"},
    "Hosen": {"Rate": 0.00, "PB": 0.00, "Ticker": "5EV", "Sector": "Consumer Defensive"},
    "Indofood Agri": {"Rate": 0.00, "PB": 0.00, "Ticker": "5JS", "Sector": "Consumer Defensive"},
    "JB Foods": {"Rate": 0.00, "PB": 0.00, "Ticker": "BEW", "Sector": "Consumer Defensive"},
    "Kencana Agri": {"Rate": 0.00, "PB": 0.00, "Ticker": "BNE", "Sector": "Consumer Defensive"},
    "Khong Guan": {"Rate": 0.00, "PB": 0.00, "Ticker": "K03", "Sector": "Consumer Defensive"},
    "Leong Guan Hldgs": {"Rate": 0.00, "PB": 0.00, "Ticker": "LGH", "Sector": "Consumer Defensive"},
    "Mewah Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "MV4", "Sector": "Consumer Defensive"},
    "MindChamps": {"Rate": 0.00, "PB": 0.00, "Ticker": "CNE", "Sector": "Consumer Defensive"},
    "NutryFarm": {"Rate": 0.00, "PB": 0.00, "Ticker": "AZT", "Sector": "Consumer Defensive"},
    "OTS Holdings": {"Rate": 0.00, "PB": 0.00, "Ticker": "OTS", "Sector": "Consumer Defensive"},
    "Oceanus": {"Rate": 0.00, "PB": 0.00, "Ticker": "579", "Sector": "Consumer Defensive"},
    "Olam Group": {"Rate": 0.07, "PB": 0.58, "Ticker": "VC2", "Sector": "Consumer Defensive"},
    "Overseas Edu": {"Rate": 0.00, "PB": 0.00, "Ticker": "RQ1", "Sector": "Consumer Defensive"},
    "Pacific Andes": {"Rate": 0.00, "PB": 0.00, "Ticker": "P11", "Sector": "Consumer Defensive"},
    "QAF": {"Rate": 0.00, "PB": 0.00, "Ticker": "Q01", "Sector": "Consumer Defensive"},
    "Raffles Edu": {"Rate": 0.00, "PB": 0.00, "Ticker": "NR7", "Sector": "Consumer Defensive"},
    "Sheng Siong": {"Rate": 0.00, "PB": 0.00, "Ticker": "OV8", "Sector": "Consumer Defensive"},
    "Shenshan": {"Rate": 0.00, "PB": 0.00, "Ticker": "BKV", "Sector": "Consumer Defensive"},
    "Sino Grandness": {"Rate": 0.00, "PB": 0.00, "Ticker": "T4B", "Sector": "Consumer Defensive"},
    "SunMoonFood": {"Rate": 0.00, "PB": 0.00, "Ticker": "AAJ", "Sector": "Consumer Defensive"},
    "Suntar Eco-City": {"Rate": 0.00, "PB": 0.00, "Ticker": "BKZ", "Sector": "Consumer Defensive"},
    "TSH Resources": {"Rate": 0.00, "PB": 0.00, "Ticker": "TSH", "Sector": "Consumer Defensive"},
    "ThaiBev": {"Rate": 0.00, "PB": 0.00, "Ticker": "Y92", "Sector": "Consumer Defensive"},
    "United Food": {"Rate": 0.00, "PB": 0.00, "Ticker": "AZR", "Sector": "Consumer Defensive"},
    "Wilmar Intl": {"Rate": 0.17, "PB": 0.78, "Ticker": "F34", "Sector": "Consumer Defensive"},
    "Yeo Hiap Seng": {"Rate": 0.00, "PB": 0.00, "Ticker": "Y03", "Sector": "Consumer Defensive"},
    "Zhongxin Fruit": {"Rate": 0.00, "PB": 0.00, "Ticker": "5EG", "Sector": "Consumer Defensive"},
    "Zixin": {"Rate": 0.00, "PB": 0.00, "Ticker": "42W", "Sector": "Consumer Defensive"},
    "AMOS Group": {"Rate": 0.00, "PB": 0.00, "Ticker": "49B", "Sector": "Energy"},
    "AP Oil": {"Rate": 0.00, "PB": 0.00, "Ticker": "5AU", "Sector": "Energy"},
    "Advanced": {"Rate": 0.00, "PB": 0.00, "Ticker": "BLZ", "Sector": "Energy"},
    "AnAn Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "Y35", "Sector": "Energy"},
    "Annica": {"Rate": 0.00, "PB": 0.00, "Ticker": "5AL", "Sector": "Energy"},
    "Asian Micro": {"Rate": 0.00, "PB": 0.00, "Ticker": "585", "Sector": "Energy"},
    "Baker Technology": {"Rate": 0.00, "PB": 0.00, "Ticker": "BTP", "Sector": "Energy"},
    "Beng Kuang": {"Rate": 0.00, "PB": 0.00, "Ticker": "BEZ", "Sector": "Energy"},
    "BlackGoldNatural": {"Rate": 0.00, "PB": 0.00, "Ticker": "41H", "Sector": "Energy"},
    "CH Offshore": {"Rate": 0.00, "PB": 0.00, "Ticker": "C13", "Sector": "Energy"},
    "CapAllianz": {"Rate": 0.00, "PB": 0.00, "Ticker": "594", "Sector": "Energy"},
    "China Aviation": {"Rate": 0.00, "PB": 0.00, "Ticker": "G92", "Sector": "Energy"},
    "Coolan Group": {"Rate": 0.00, "PB": 0.00, "Ticker": "BMT", "Sector": "Energy"},
    "Ezra": {"Rate": 0.00, "PB": 0.00, "Ticker": "5DN", "Sector": "Energy"},
    "Federal Int": {"Rate": 0.00, "PB": 0.00, "Ticker": "BDU", "Sector": "Energy"},
    "Geo Energy Res": {"Rate": 0.00, "PB": 0.00, "Ticker": "RE4", "Sector": "Energy"},
    "Heatec Jietong": {"Rate": 0.00, "PB": 0.00, "Ticker": "5OR", "Sector": "Energy"},
    "Hengyang Petro": {"Rate": 0.00, "PB": 0.00, "Ticker": "5PD", "Sector": "Energy"},
    "Interra Resource": {"Rate": 0.00, "PB": 0.00, "Ticker": "5GI", "Sector": "Energy"},
    "Kim Heng": {"Rate": 0.00, "PB": 0.00, "Ticker": "5G2", "Sector": "Energy"},
    "MTQ": {"Rate": 0.00, "PB": 0.00, "Ticker": "M05", "Sector": "Energy"},
    "Mencast": {"Rate": 0.00, "PB": 0.00, "Ticker": "5NF", "Sector": "Energy"},
    "Mermaid Maritime": {"Rate": 0.00, "PB": 0.00, "Ticker": "DU4", "Sector": "Energy"},
    "RH PetroGas": {"Rate": 0.00, "PB": 0.00, "Ticker": "T13", "Sector": "Energy"},
    "Rex Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "5WH", "Sector": "Energy"},
    "Seatrium Ltd": {"Rate": 0.02, "PB": 1.10, "Ticker": "500", "Sector": "Energy"},
    "Sinostar Pec": {"Rate": 0.00, "PB": 0.00, "Ticker": "C9Q", "Sector": "Energy"},
    "Teho Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "5OQ", "Sector": "Energy"},
    "Universal Res": {"Rate": 0.00, "PB": 0.00, "Ticker": "BGO", "Sector": "Energy"},
    "AMTD IDEA OV": {"Rate": 0.00, "PB": 0.00, "Ticker": "HKB", "Sector": "Financial Services"},
    "B&M Hldg": {"Rate": 0.00, "PB": 0.00, "Ticker": "CJN", "Sector": "Financial Services"},
    "CreditBureauAsia": {"Rate": 0.00, "PB": 2.34, "Ticker": "TCU", "Sector": "Financial Services"},
    "DBS": {"Rate": 3.24, "PB": 2.36, "Ticker": "D05", "Sector": "Financial Services"},
    "Global Inv": {"Rate": 0.00, "PB": 0.00, "Ticker": "B73", "Sector": "Financial Services"},
    "Great Eastern": {"Rate": 0.00, "PB": 0.00, "Ticker": "G07", "Sector": "Financial Services"},
    "Heptamax": {"Rate": 0.00, "PB": 0.00, "Ticker": "8A1", "Sector": "Financial Services"},
    "Hong Leong Fin": {"Rate": 0.00, "PB": 0.00, "Ticker": "S41", "Sector": "Financial Services"},
    "Hotung Inv": {"Rate": 0.00, "PB": 0.00, "Ticker": "BLS", "Sector": "Financial Services"},
    "IFS Capital": {"Rate": 0.00, "PB": 0.00, "Ticker": "I49", "Sector": "Financial Services"},
    "Joyas Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "E9L", "Sector": "Financial Services"},
    "Luminor": {"Rate": 0.00, "PB": 0.00, "Ticker": "5UA", "Sector": "Financial Services"},
    "Net Pac Hldgs": {"Rate": 0.00, "PB": 0.00, "Ticker": "5QY", "Sector": "Financial Services"},
    "Nomura Yen1k": {"Rate": 0.00, "PB": 0.00, "Ticker": "N33", "Sector": "Financial Services"},
    "OCBC Bank": {"Rate": 0.99, "PB": 1.18, "Ticker": "O39", "Sector": "Financial Services"},
    "Pacific Century": {"Rate": 0.00, "PB": 0.00, "Ticker": "P15", "Sector": "Financial Services"},
    "Prudential USD": {"Rate": 0.00, "PB": 0.00, "Ticker": "K6S", "Sector": "Financial Services"},
    "SGX": {"Rate": 0.00, "PB": 0.00, "Ticker": "S68", "Sector": "Financial Services"},
    "Sing Inv & Fin": {"Rate": 0.00, "PB": 0.00, "Ticker": "S35", "Sector": "Financial Services"},
    "Spura Finance": {"Rate": 0.00, "PB": 0.00, "Ticker": "S23", "Sector": "Financial Services"},
    "TIH": {"Rate": 0.00, "PB": 0.00, "Ticker": "T55", "Sector": "Financial Services"},
    "Trendlines": {"Rate": 0.00, "PB": 0.00, "Ticker": "42T", "Sector": "Financial Services"},
    "UOB": {"Rate": 1.70, "PB": 1.6, "Ticker": "U11", "Sector": "Financial Services"},
    "UOB Kay Hian": {"Rate": 0.00, "PB": 0.00, "Ticker": "U10", "Sector": "Financial Services"},
    "UOI": {"Rate": 0.00, "PB": 0.00, "Ticker": "U13", "Sector": "Financial Services"},
    "YZJ Fin Hldg": {"Rate": 0.00, "PB": 0.00, "Ticker": "YF8", "Sector": "Financial Services"},
    "YZJ Maritime": {"Rate": 0.00, "PB": 0.00, "Ticker": "8YZ", "Sector": "Financial Services"},
    "AJJ Medtech": {"Rate": 0.00, "PB": 0.00, "Ticker": "584", "Sector": "Healthcare"},
    "Accrelist Ltd": {"Rate": 0.00, "PB": 0.00, "Ticker": "QZG", "Sector": "Healthcare"},
    "Alliance HC": {"Rate": 0.00, "PB": 0.00, "Ticker": "MIJ", "Sector": "Healthcare"},
    "Aoxin Q & M": {"Rate": 0.00, "PB": 0.00, "Ticker": "1D4", "Sector": "Healthcare"},
    "Asia Vets": {"Rate": 0.00, "PB": 0.00, "Ticker": "5RE", "Sector": "Healthcare"},
    "AsiaMedic": {"Rate": 0.00, "PB": 0.00, "Ticker": "505", "Sector": "Healthcare"},
    "B Wilshire Ltd": {"Rate": 0.00, "PB": 0.00, "Ticker": "9QX", "Sector": "Healthcare"},
    "CMS": {"Rate": 0.00, "PB": 0.00, "Ticker": "8A8", "Sector": "Healthcare"},
    "Clearbridge": {"Rate": 0.00, "PB": 0.00, "Ticker": "1H3", "Sector": "Healthcare"},
    "Cordlife": {"Rate": 0.00, "PB": 0.00, "Ticker": "P8A", "Sector": "Healthcare"},
    "EFH Ltd": {"Rate": 0.00, "PB": 0.00, "Ticker": "8YY", "Sector": "Healthcare"},
    "HC Surgical": {"Rate": 0.00, "PB": 0.00, "Ticker": "1B1", "Sector": "Healthcare"},
    "Haw Par": {"Rate": 0.00, "PB": 0.00, "Ticker": "H02", "Sector": "Healthcare"},
    "Hyphens Pharma": {"Rate": 0.00, "PB": 0.00, "Ticker": "1J5", "Sector": "Healthcare"},
    "IHH": {"Rate": 0.00, "PB": 0.00, "Ticker": "Q0F", "Sector": "Healthcare"},
    "ISEC": {"Rate": 0.00, "PB": 0.00, "Ticker": "40T", "Sector": "Healthcare"},
    "IX Biopharma": {"Rate": 0.00, "PB": 0.00, "Ticker": "42C", "Sector": "Healthcare"},
    "Livingstone": {"Rate": 0.00, "PB": 0.00, "Ticker": "PRH", "Sector": "Healthcare"},
    "Lonza": {"Rate": 0.00, "PB": 0.00, "Ticker": "O6Z", "Sector": "Healthcare"},
    "MediLifestyle": {"Rate": 0.00, "PB": 0.00, "Ticker": "Z4D", "Sector": "Healthcare"},
    "Medinex": {"Rate": 0.00, "PB": 0.00, "Ticker": "OTX", "Sector": "Healthcare"},
    "Medtecs Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "546", "Sector": "Healthcare"},
    "Meta Health": {"Rate": 0.00, "PB": 0.00, "Ticker": "5DX", "Sector": "Healthcare"},
    "OUE Healthcare": {"Rate": 0.00, "PB": 0.00, "Ticker": "5WA", "Sector": "Healthcare"},
    "Pasture Holdings": {"Rate": 0.00, "PB": 0.00, "Ticker": "UUK", "Sector": "Healthcare"},
    "Pharmesis Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "BFK", "Sector": "Healthcare"},
    "Q&M Dental": {"Rate": 0.00, "PB": 0.00, "Ticker": "QC7", "Sector": "Healthcare"},
    "Quantum Health": {"Rate": 0.00, "PB": 0.00, "Ticker": "V8Y", "Sector": "Healthcare"},
    "Raffles Medical": {"Rate": 0.00, "PB": 0.00, "Ticker": "BSL", "Sector": "Healthcare"},
    "Riverstone": {"Rate": 0.00, "PB": 0.00, "Ticker": "AP4", "Sector": "Healthcare"},
    "SAM Holdings": {"Rate": 0.00, "PB": 0.00, "Ticker": "9G2", "Sector": "Healthcare"},
    "Sing Paincare": {"Rate": 0.00, "PB": 0.00, "Ticker": "FRQ", "Sector": "Healthcare"},
    "TJ DaRenTang USD": {"Rate": 0.00, "PB": 0.00, "Ticker": "T14", "Sector": "Healthcare"},
    "Thomson Medical": {"Rate": 0.00, "PB": 0.00, "Ticker": "A50", "Sector": "Healthcare"},
    "Top Glove": {"Rate": 0.00, "PB": 0.00, "Ticker": "BVA", "Sector": "Healthcare"},
    "UGHealthcare": {"Rate": 0.00, "PB": 0.00, "Ticker": "8K7", "Sector": "Healthcare"},
    "ULTRAGREEN AI USD": {"Rate": 0.00, "PB": 0.00, "Ticker": "ULG", "Sector": "Healthcare"},
    "UpHealth Group": {"Rate": 0.00, "PB": 0.00, "Ticker": "GRQ", "Sector": "Healthcare"},
    "Vicplas Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "569", "Sector": "Healthcare"},
    "A-Smart": {"Rate": 0.00, "PB": 0.00, "Ticker": "BQC", "Sector": "Industrials"},
    "A-Sonic Aero": {"Rate": 0.00, "PB": 0.00, "Ticker": "BTJ", "Sector": "Industrials"},
    "ASL Marine": {"Rate": 0.00, "PB": 0.00, "Ticker": "A04", "Sector": "Industrials"},
    "Abundante": {"Rate": 0.00, "PB": 0.00, "Ticker": "570", "Sector": "Industrials"},
    "Acesian Partners": {"Rate": 0.00, "PB": 0.00, "Ticker": "5FW", "Sector": "Industrials"},
    "AcroMeta": {"Rate": 0.00, "PB": 0.00, "Ticker": "43F", "Sector": "Industrials"},
    "Advancer Global": {"Rate": 0.00, "PB": 0.00, "Ticker": "43Q", "Sector": "Industrials"},
    "Adventus": {"Rate": 0.00, "PB": 0.00, "Ticker": "5EF", "Sector": "Industrials"},
    "Aedge Group": {"Rate": 0.00, "PB": 0.00, "Ticker": "XVG", "Sector": "Industrials"},
    "Atlantic Nav": {"Rate": 0.00, "PB": 0.00, "Ticker": "5UL", "Sector": "Industrials"},
    "Attika Group": {"Rate": 0.00, "PB": 0.00, "Ticker": "53W", "Sector": "Industrials"},
    "Audience": {"Rate": 0.00, "PB": 0.00, "Ticker": "1AZ", "Sector": "Industrials"},
    "AusGroup": {"Rate": 0.00, "PB": 0.00, "Ticker": "5GJ", "Sector": "Industrials"},
    "Avarga Ltd": {"Rate": 0.00, "PB": 0.00, "Ticker": "X5N", "Sector": "Industrials"},
    "BBR": {"Rate": 0.00, "PB": 0.00, "Ticker": "KJ5", "Sector": "Industrials"},
    "BH Global": {"Rate": 0.00, "PB": 0.00, "Ticker": "BQN", "Sector": "Industrials"},
    "Boldtek": {"Rate": 0.00, "PB": 0.00, "Ticker": "5VI", "Sector": "Industrials"},
    "Boustead": {"Rate": 0.00, "PB": 0.00, "Ticker": "F9D", "Sector": "Industrials"},
    "Brook Crompton": {"Rate": 0.00, "PB": 0.00, "Ticker": "AWC", "Sector": "Industrials"},
    "CFM": {"Rate": 0.00, "PB": 0.00, "Ticker": "5EB", "Sector": "Industrials"},
    "COSCO SHP SG": {"Rate": 0.00, "PB": 0.00, "Ticker": "F83", "Sector": "Industrials"},
    "CSC": {"Rate": 0.00, "PB": 0.00, "Ticker": "C06", "Sector": "Industrials"},
    "Chasen": {"Rate": 0.00, "PB": 0.00, "Ticker": "5NV", "Sector": "Industrials"},
    "ChinaKundaTech": {"Rate": 0.00, "PB": 0.00, "Ticker": "GU5", "Sector": "Industrials"},
    "Civmec": {"Rate": 0.00, "PB": 0.00, "Ticker": "P9D", "Sector": "Industrials"},
    "ComfortDelGro": {"Rate": 0.07, "PB": 1.05, "Ticker": "C52", "Sector": "Industrials"},
    "Courage Inv": {"Rate": 0.00, "PB": 0.00, "Ticker": "CIN", "Sector": "Industrials"},
    "Darco Water Tech": {"Rate": 0.00, "PB": 0.00, "CAPITATicker": "BLR", "Sector": "Industrials"},
    "Dezign Format": {"Rate": 0.00, "PB": 0.00, "Ticker": "UZF", "Sector": "Industrials"},
    "ES": {"Rate": 0.00, "PB": 0.00, "Ticker": "5RC", "Sector": "Industrials"},
    "EcoWise": {"Rate": 0.00, "PB": 0.00, "Ticker": "5CT", "Sector": "Industrials"},
    "Eindec": {"Rate": 0.00, "PB": 0.00, "Ticker": "42Z", "Sector": "Industrials"},
    "Eneco Energy": {"Rate": 0.00, "PB": 0.00, "Ticker": "R14", "Sector": "Industrials"},
    "Enviro-Hub": {"Rate": 0.00, "PB": 0.00, "Ticker": "L23", "Sector": "Industrials"},
    "Ever Glory": {"Rate": 0.00, "PB": 0.00, "Ticker": "ZKX", "Sector": "Industrials"},
    "FSL Trust": {"Rate": 0.00, "PB": 0.00, "Ticker": "D8DU", "Sector": "Industrials"},
    "Far East": {"Rate": 0.00, "PB": 0.00, "Ticker": "5TJ", "Sector": "Industrials"},
    "Fu Yu": {"Rate": 0.00, "PB": 0.00, "Ticker": "F13", "Sector": "Industrials"},
    "Fuji Offset": {"Rate": 0.00, "PB": 0.00, "Ticker": "508", "Sector": "Industrials"},
    "GDS Global": {"Rate": 0.00, "PB": 0.00, "Ticker": "5VP", "Sector": "Industrials"},
    "GKE": {"Rate": 0.00, "PB": 0.00, "Ticker": "595", "Sector": "Industrials"},
    "GP Industries": {"Rate": 0.00, "PB": 0.00, "Ticker": "G20", "Sector": "Industrials"},
    "GSH": {"Rate": 0.00, "PB": 0.00, "Ticker": "BDX", "Sector": "Industrials"},
    "Green Build": {"Rate": 0.00, "PB": 0.00, "Ticker": "Y06", "Sector": "Industrials"},
    "HGH": {"Rate": 0.00, "PB": 0.00, "Ticker": "5GZ", "Sector": "Industrials"},
    "HPH Trust SGD": {"Rate": 0.00, "PB": 0.00, "Ticker": "P7VU", "Sector": "Industrials"},
    "HPH Trust USD": {"Rate": 0.02, "PB": 0.35, "Ticker": "NS8U", "Sector": "Industrials"},
    "HRnetGroup": {"Rate": 0.00, "PB": 0.00, "Ticker": "CHZ", "Sector": "Industrials"},
    "Hafary": {"Rate": 0.00, "PB": 0.00, "Ticker": "5VS", "Sector": "Industrials"},
    "Hiap Seng Ind": {"Rate": 0.00, "PB": 0.00, "Ticker": "1L2", "Sector": "Industrials"},
    "Hiap Tong": {"Rate": 0.00, "PB": 0.00, "Ticker": "5PO", "Sector": "Industrials"},
    "Hock Lian Seng": {"Rate": 0.00, "PB": 0.00, "Ticker": "J2T", "Sector": "Industrials"},
    "Hoe Leong": {"Rate": 0.00, "PB": 0.00, "Ticker": "H20", "Sector": "Industrials"},
    "Hor Kew": {"Rate": 0.00, "PB": 0.00, "Ticker": "BBP", "Sector": "Industrials"},
    "Huationg Global": {"Rate": 0.00, "PB": 0.00, "Ticker": "41B", "Sector": "Industrials"},
    "IPS Securex": {"Rate": 0.00, "PB": 0.00, "Ticker": "42N", "Sector": "Industrials"},
    "ISDN": {"Rate": 0.00, "PB": 0.00, "Ticker": "I07", "Sector": "Industrials"},
    "ISOTeam": {"Rate": 0.00, "PB": 0.00, "Ticker": "5WF", "Sector": "Industrials"},
    "InnoTek": {"Rate": 0.00, "PB": 0.00, "Ticker": "M14", "Sector": "Industrials"},
    "Intraco": {"Rate": 0.00, "PB": 0.00, "Ticker": "I06", "Sector": "Industrials"},
    "JEP": {"Rate": 0.00, "PB": 0.00, "Ticker": "1J4", "Sector": "Industrials"},
    "JMH USD": {"Rate": 0.00, "PB": 0.00, "Ticker": "J36", "Sector": "Industrials"},
    "Jardine C&C": {"Rate": 0.00, "PB": 0.00, "Ticker": "C07", "Sector": "Industrials"},
    "KIN": {"Rate": 0.00, "PB": 0.00, "Ticker": "KIN", "Sector": "Industrials"},
    "KSH": {"Rate": 0.00, "PB": 0.00, "Ticker": "ER0", "Sector": "Industrials"},
    "Keong Hong": {"Rate": 0.00, "PB": 0.00, "Ticker": "5TT", "Sector": "Industrials"},
    "Keppel": {"Rate": 0.47, "PB": 1.15, "Ticker": "BN4", "Sector": "Industrials"},
    "King Wan": {"Rate": 0.00, "PB": 0.00, "Ticker": "554", "Sector": "Industrials"},
    "KingsmenCreative": {"Rate": 0.00, "PB": 0.00, "Ticker": "5MZ", "Sector": "Industrials"},
    "Koh Bros": {"Rate": 0.00, "PB": 0.00, "Ticker": "K75", "Sector": "Industrials"},
    "Koh Eco": {"Rate": 0.00, "PB": 0.00, "Ticker": "5HV", "Sector": "Industrials"},
    "Kori": {"Rate": 0.00, "PB": 0.00, "Ticker": "5VC", "Sector": "Industrials"},
    "Koyo Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "5OC", "Sector": "Industrials"},
    "LMS Compliance": {"Rate": 0.00, "PB": 0.00, "Ticker": "LMS", "Sector": "Industrials"},
    "LS 2 Holdings": {"Rate": 0.00, "PB": 0.00, "Ticker": "ENV", "Sector": "Industrials"},
    "Leader Env": {"Rate": 0.00, "PB": 0.00, "Ticker": "LS9", "Sector": "Industrials"},
    "Ley Choon": {"Rate": 0.00, "PB": 0.00, "Ticker": "Q0X", "Sector": "Industrials"},
    "Lincotrade": {"Rate": 0.00, "PB": 0.00, "Ticker": "BFT", "Sector": "Industrials"},
    "Lum Chang": {"Rate": 0.00, "PB": 0.00, "Ticker": "L19", "Sector": "Industrials"},
    "Lum Chang Creat": {"Rate": 0.00, "PB": 0.00, "Ticker": "LCC", "Sector": "Industrials"},
    "MarcoPolo Marine": {"Rate": 0.00, "PB": 0.00, "Ticker": "5LY", "Sector": "Industrials"},
    "Metech Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "V3M", "Sector": "Industrials"},
    "Miyoshi": {"Rate": 0.00, "PB": 0.00, "Ticker": "M03", "Sector": "Industrials"},
    "Mooreast": {"Rate": 0.00, "PB": 0.00, "Ticker": "1V3", "Sector": "Industrials"},
    "Mun Siong Engg": {"Rate": 0.00, "PB": 0.00, "Ticker": "MF6", "Sector": "Industrials"},
    "Nam Lee Metal": {"Rate": 0.00, "PB": 0.00, "Ticker": "G0I", "Sector": "Industrials"},
    "NamCheong": {"Rate": 0.00, "PB": 0.00, "Ticker": "1MZ", "Sector": "Industrials"},
    "Natural Cool": {"Rate": 0.00, "PB": 0.00, "Ticker": "5IF", "Sector": "Industrials"},
    "Nordic": {"Rate": 0.00, "PB": 0.00, "Ticker": "MR7", "Sector": "Industrials"},
    "OKP": {"Rate": 0.00, "PB": 0.00, "Ticker": "5CF", "Sector": "Industrials"},
    "Ocean Sky Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "1B6", "Sector": "Industrials"},
    "OceanScape Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "V2Y", "Sector": "Industrials"},
    "Oiltek": {"Rate": 0.00, "PB": 0.00, "Ticker": "HQU", "Sector": "Industrials"},
    "PacificRadiance": {"Rate": 0.00, "PB": 0.00, "Ticker": "RXS", "Sector": "Industrials"},
    "Penguin Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "BTM", "Sector": "Industrials"},
    "Progen": {"Rate": 0.00, "PB": 0.00, "Ticker": "583", "Sector": "Industrials"},
    "Raffles Infrastructure": {"Rate": 0.00, "PB": 0.00, "Ticker": "LUY", "Sector": "Industrials"},
    "Reclaims Global": {"Rate": 0.00, "PB": 0.00, "Ticker": "NEX", "Sector": "Industrials"},
    "ResourcesGbl": {"Rate": 0.00, "PB": 0.00, "Ticker": "V7R", "Sector": "Industrials"},
    "SATS": {"Rate": 0.05, "PB": 1.85, "Ticker": "S58", "Sector": "Industrials"},
    "SBS Transit": {"Rate": 0.00, "PB": 0.00, "Ticker": "S61", "Sector": "Industrials"},
    "SHS": {"Rate": 0.00, "PB": 0.00, "Ticker": "566", "Sector": "Industrials"},
    "SIA": {"Rate": 0.00, "PB": 0.00, "Ticker": "C6L", "Sector": "Industrials"},
    "SIA Engineering": {"Rate": 0.08, "PB": 1.25, "Ticker": "S59", "Sector": "Industrials"},
    "ST Engineering": {"Rate": 0.16, "PB": 4.50, "Ticker": "S63", "Sector": "Industrials"},
    "Salt Investments": {"Rate": 0.00, "PB": 0.00, "Ticker": "FQ7", "Sector": "Industrials"},
    "SamuderaShipping": {"Rate": 0.00, "PB": 0.00, "Ticker": "S56", "Sector": "Industrials"},
    "Sanli Env": {"Rate": 0.00, "PB": 0.00, "Ticker": "1000", "Sector": "Industrials"},
    "Sapphire": {"Rate": 0.00, "PB": 0.00, "Ticker": "BRD", "Sector": "Industrials"},
    "Secura": {"Rate": 0.00, "PB": 0.00, "Ticker": "43B", "Sector": "Industrials"},
    "Sevens Atelier": {"Rate": 0.00, "PB": 0.00, "Ticker": "5EW", "Sector": "Industrials"},
    "Shanaya": {"Rate": 0.00, "PB": 0.00, "Ticker": "SES", "Sector": "Industrials"},
    "Shanghai Turbo": {"Rate": 0.00, "PB": 0.00, "Ticker": "AWM", "Sector": "Industrials"},
    "Sheffield Green": {"Rate": 0.00, "PB": 0.00, "Ticker": "SGR", "Sector": "Industrials"},
    "Sin Heng Mach": {"Rate": 0.00, "PB": 0.00, "Ticker": "BKA", "Sector": "Industrials"},
    "SingPost": {"Rate": 0.00, "PB": 0.00, "Ticker": "S08", "Sector": "Industrials"},
    "SingShipping": {"Rate": 0.00, "PB": 0.00, "Ticker": "S19", "Sector": "Industrials"},
    "Skylink": {"Rate": 0.00, "PB": 0.00, "Ticker": "XZB", "Sector": "Industrials"},
    "SoilbuildConstr": {"Rate": 0.00, "PB": 0.00, "Ticker": "ZQM", "Sector": "Industrials"},
    "Southern Arch": {"Rate": 0.00, "PB": 0.00, "Ticker": "A33", "Sector": "Industrials"},
    "TA": {"Rate": 0.00, "PB": 0.00, "Ticker": "PA3", "Sector": "Industrials"},
    "Tai Sin Electric": {"Rate": 0.00, "PB": 0.00, "Ticker": "500", "Sector": "Industrials"},
    "Tiong Seng": {"Rate": 0.00, "PB": 0.00, "Ticker": "BFI", "Sector": "Industrials"},
    "Tiong Woon": {"Rate": 0.00, "PB": 0.00, "Ticker": "BQM", "Sector": "Industrials"},
    "Tritech": {"Rate": 0.00, "PB": 0.00, "Ticker": "5G9", "Sector": "Industrials"},
    "Triyards": {"Rate": 0.00, "PB": 0.00, "Ticker": "RC5", "Sector": "Industrials"},
    "Tye Soon": {"Rate": 0.00, "PB": 0.00, "Ticker": "BFU", "Sector": "Industrials"},
    "USP Group": {"Rate": 0.00, "PB": 0.00, "Ticker": "BRS", "Sector": "Industrials"},
    "Uni-Asia Grp": {"Rate": 0.00, "PB": 0.00, "Ticker": "CHJ", "Sector": "Industrials"},
    "UnionSteel": {"Rate": 0.00, "PB": 0.00, "Ticker": "ZB9", "Sector": "Industrials"},
    "VCPlus": {"Rate": 0.00, "PB": 0.00, "Ticker": "43E", "Sector": "Industrials"},
    "Vallianz": {"Rate": 0.00, "PB": 0.00, "Ticker": "WPC", "Sector": "Industrials"},
    "Versalink": {"Rate": 0.00, "PB": 0.00, "Ticker": "40N", "Sector": "Industrials"},
    "Vibrant Group": {"Rate": 0.00, "PB": 0.00, "Ticker": "BIP", "Sector": "Industrials"},
    "VibroPower": {"Rate": 0.00, "PB": 0.00, "Ticker": "BJD", "Sector": "Industrials"},
    "Wee Hur": {"Rate": 0.00, "PB": 0.00, "Ticker": "E3B", "Sector": "Industrials"},
    "Wong Fong Ind": {"Rate": 0.00, "PB": 0.00, "Ticker": "1A1", "Sector": "Industrials"},
    "World Precision": {"Rate": 0.00, "PB": 0.00, "Ticker": "B49", "Sector": "Industrials"},
    "XMH": {"Rate": 0.00, "PB": 0.00, "Ticker": "BQF", "Sector": "Industrials"},
    "YZJ Shipbldg CNY": {"Rate": 0.00, "PB": 0.00, "Ticker": "SO7", "Sector": "Industrials"},
    "YZJ Shipbldg SGD": {"Rate": 0.00, "PB": 0.00, "Ticker": "BS6", "Sector": "Industrials"},
    "Yoma Strategic": {"Rate": 0.00, "PB": 0.00, "Ticker": "Z59", "Sector": "Industrials"},
    "Yongmao": {"Rate": 0.00, "PB": 0.00, "Ticker": "BKX", "Sector": "Industrials"},
    "ZICO Hldgs": {"Rate": 0.00, "PB": 0.00, "Ticker": "40W", "Sector": "Industrials"},
    "AIMS APAC Reit": {"Rate": 0.00, "PB": 0.00, "Ticker": "O5RU", "Sector": "REITs & Business Trusts"},
    "APAC Realty": {"Rate": 0.00, "PB": 0.00, "Ticker": "CLN", "Sector": "Real Estate"},
    "Acro HTrust USD": {"Rate": 0.00, "PB": 0.00, "Ticker": "XZL", "Sector": "REITs & Business Trusts"},
    "Alpha Integrated REIT": {"Rate": 0.00, "PB": 0.00, "Ticker": "M1GU", "Sector": "REITs & Business Trusts"},
    "Alset": {"Rate": 0.00, "PB": 0.00, "Ticker": "40V", "Sector": "Real Estate"},
    "Amcorp Global": {"Rate": 0.00, "PB": 0.00, "Ticker": "S9B", "Sector": "Real Estate"},
    "Amplefield Ltd": {"Rate": 0.00, "PB": 0.00, "Ticker": "AOF", "Sector": "Real Estate"},
    "Aspen": {"Rate": 0.00, "PB": 0.00, "Ticker": "1F3", "Sector": "Real Estate"},
    "Astaka": {"Rate": 0.00, "PB": 0.00, "Ticker": "42S", "Sector": "Real Estate"},
    "BHG Retail Reit": {"Rate": 0.00, "PB": 0.00, "Ticker": "BMGU", "Sector": "REITs & Business Trusts"},
    "Bukit Sembawang": {"Rate": 0.00, "PB": 0.00, "Ticker": "B61", "Sector": "Real Estate"},
    "Bund Center": {"Rate": 0.00, "PB": 0.00, "Ticker": "BTE", "Sector": "Real Estate"},
    "CDL HTrust": {"Rate": 0.08, "PB": 0.62, "Ticker": "J85", "Sector": "REITs & Business Trusts"},
    "CapLand Ascendas REIT": {"Rate": 0.00, "PB": 0.00, "Ticker": "A17U", "Sector": "REITs & Business Trusts"},
    "CapLand Ascott T": {"Rate": 0.061, "PB": 0.00, "Ticker": "HMN", "Sector": "REITs & Business Trusts"},
    "Capita China TR": {"Rate": 0.047, "PB": 0.62, "Ticker": "AU8U", "Sector": "REITs & Business Trusts"},
    "CapLand India T": {"Rate": 0.08, "PB": 1.12, "Ticker": "CY6U", "Sector": "REITs & Business Trusts"},
    "CapLand IntCom T": {"Rate": 0.00, "PB": 0.00, "Ticker": "C38U", "Sector": "REITs & Business Trusts"},
    "CapitaLandInvest": {"Rate": 0.00, "PB": 0.00, "Ticker": "9CI", "Sector": "REITs & Business Trusts"},
    "Capital World": {"Rate": 0.00, "PB": 0.00, "Ticker": "1D5", "Sector": "REITs & Business Trusts"},
    "Cent Accom REIT": {"Rate": 0.00, "PB": 0.00, "Ticker": "8C8U", "Sector": "REITs & Business Trusts"},
    "China Yuanbang": {"Rate": 0.00, "PB": 0.00, "Ticker": "BCD", "Sector": "Real Estate"},
    "Chuan Hup": {"Rate": 0.00, "PB": 0.00, "Ticker": "C33", "Sector": "Real Estate"},
    "CityDev": {"Rate": 0.12, "PB": 0.38, "Ticker": "C09", "Sector": "Real Estate"},
    "Coliwoo Hldgs": {"Rate": 0.00, "PB": 0.00, "Ticker": "W8W", "Sector": "Real Estate"},
    "Daiwa Hse Log Tr": {"Rate": 0.00, "PB": 0.00, "Ticker": "DHLU", "Sector": "Real Estate"},
    "Dasin Retail Tr": {"Rate": 0.00, "PB": 0.00, "Ticker": "CEDU", "Sector": "REITs & Business Trusts"},
    "Debao Property": {"Rate": 0.00, "PB": 0.00, "Ticker": "BTF", "Sector": "Real Estate"},
    "DigiCore Reit USD": {"Rate": 0.00, "PB": 0.00, "Ticker": "DCRU", "Sector": "REITs & Business Trusts"},
    "EC World Reit": {"Rate": 0.00, "PB": 0.00, "Ticker": "BWCU", "Sector": "REITs & Business Trusts"},
    "ESR REIT": {"Rate": 0.00, "PB": 0.00, "Ticker": "9A4U", "Sector": "REITs & Business Trusts"},
    "ETC Singapore": {"Rate": 0.00, "PB": 0.00, "Ticker": "1C0", "Sector": "Real Estate"},
    "Eagle HTrust USD": {"Rate": 0.00, "PB": 0.00, "Ticker": "LIW", "Sector": "REITs & Business Trusts"},
    "EliteUKREIT GBP": {"Rate": 0.00, "PB": 0.00, "Ticker": "MXNU", "Sector": "REITs & Business Trusts"},
    "Far East HTrust": {"Rate": 0.00, "PB": 0.00, "Ticker": "Q5T", "Sector": "REITs & Business Trusts"},
    "Far East Orchard": {"Rate": 0.00, "PB": 0.00, "Ticker": "O10", "Sector": "Real Estate"},
    "Figtree": {"Rate": 0.00, "PB": 0.00, "Ticker": "5F4", "Sector": "Real Estate"},
    "First Reit": {"Rate": 0.02, "PB": 0.55, "Ticker": "AW9U", "Sector": "REITs & Business Trusts"},
    "First Sponsor": {"Rate": 0.00, "PB": 0.00, "Ticker": "ADN", "Sector": "Real Estate"},
    "Frasers Cpt Tr": {"Rate": 0.00, "PB": 0.00, "Ticker": "J69U", "Sector": "REITs & Business Trusts"},
    "Frasers L&C Tr": {"Rate": 0.00, "PB": 0.00, "Ticker": "BUOU", "Sector": "REITs & Business Trusts"},
    "Frasers Property": {"Rate": 0.00, "PB": 0.00, "Ticker": "TQ5", "Sector": "Real Estate"},
    "GRC": {"Rate": 0.00, "PB": 0.00, "Ticker": "S3N", "Sector": "Real Estate"},
    "Goodland": {"Rate": 0.00, "PB": 0.00, "Ticker": "5PC", "Sector": "Real Estate"},
    "GuocoLand": {"Rate": 0.00, "PB": 0.00, "Ticker": "F17", "Sector": "Real Estate"},
    "Hatten Land": {"Rate": 0.00, "PB": 0.00, "Ticker": "PH0", "Sector": "Real Estate"},
    "HealthBank": {"Rate": 0.00, "PB": 0.00, "Ticker": "40B", "Sector": "Real Estate"},
    "Ho Bee Land": {"Rate": 0.00, "PB": 0.00, "Ticker": "H13", "Sector": "Real Estate"},
    "Hong Fok": {"Rate": 0.00, "PB": 0.00, "Ticker": "H30", "Sector": "Real Estate"},
    "Hong Lai Huat": {"Rate": 0.00, "PB": 0.00, "Ticker": "CTO", "Sector": "Real Estate"},
    "HongkongLand USD": {"Rate": 0.00, "PB": 0.00, "Ticker": "H78", "Sector": "Real Estate"},
    "IPC Corp": {"Rate": 0.00, "PB": 0.00, "Ticker": "AZA", "Sector": "Real Estate"},
    "IREIT Global EUR": {"Rate": 0.00, "PB": 0.00, "Ticker": "8U7U", "Sector": "REITs & Business Trusts"},
    "IREIT Global SGD": {"Rate": 0.00, "PB": 0.00, "Ticker": "UD1U", "Sector": "REITs & Business Trusts"},
    "KOP": {"Rate": 0.00, "PB": 0.00, "Ticker": "5I1", "Sector": "Real Estate"},
    "KOREReitUSD": {"Rate": 0.00, "PB": 0.00, "Ticker": "CMOU", "Sector": "REITs & Business Trusts"},
    "Keppel DC Reit": {"Rate": 0.47, "PB": 0.00, "Ticker": "AJBU", "Sector": "REITs & Business Trusts"},
    "Keppel Reit": {"Rate": 0.06, "PB": 0.62, "Ticker": "K71U", "Sector": "REITs & Business Trusts"},
    "LHN": {"Rate": 0.00, "PB": 0.00, "Ticker": "41O", "Sector": "Real Estate"},
    "Landmark REIT": {"Rate": 0.00, "PB": 0.00, "Ticker": "D5IU", "Sector": "REITs & Business Trusts"},
    "Lendlease Reit": {"Rate": 0.00, "PB": 0.00, "Ticker": "JYEU", "Sector": "REITs & Business Trusts"},
    "MYP": {"Rate": 0.00, "PB": 0.00, "Ticker": "F86", "Sector": "Real Estate"},
    "ManulifeReit USD": {"Rate": 0.00, "PB": 0.00, "Ticker": "BTOU", "Sector": "REITs & Business Trusts"},
    "Mapletree Ind Tr": {"Rate": 0.00, "PB": 0.00, "Ticker": "ME8U", "Sector": "REITs & Business Trusts"},
    "Mapletree Log Tr": {"Rate": 0.08, "PB": 0.95, "Ticker": "M44U", "Sector": "REITs & Business Trusts"},
    "Mapletree PanAsia Com Tr": {"Rate": 0.00, "PB": 0.00, "Ticker": "N2IU", "Sector": "REITs & Business Trusts"},
    "Mercurius": {"Rate": 0.00, "PB": 0.00, "Ticker": "5RF", "Sector": "Real Estate"},
    "NTT DC REIT USD": {"Rate": 0.00, "PB": 0.00, "Ticker": "NTDU", "Sector": "REITs & Business Trusts"},
    "OUE": {"Rate": 0.00, "PB": 0.00, "Ticker": "LJ3", "Sector": "Real Estate"},
    "OUEREIT": {"Rate": 0.025, "PB": 0.00, "Ticker": "TS0U", "Sector": "REITs & Business Trusts"},
    "Olive Tree": {"Rate": 0.00, "PB": 0.00, "Ticker": "1H2", "Sector": "Real Estate"},
    "OneApex": {"Rate": 0.00, "PB": 0.00, "Ticker": "5SY", "Sector": "Real Estate"},
    "Oxley": {"Rate": 0.00, "PB": 0.00, "Ticker": "5UX", "Sector": "Real Estate"},
    "Pan Hong": {"Rate": 0.00, "PB": 0.00, "Ticker": "P36", "Sector": "Real Estate"},
    "ParkwayLife Reit": {"Rate": 0.00, "PB": 0.00, "Ticker": "C2PU", "Sector": "REITs & Business Trusts"},
    "Pollux Prop": {"Rate": 0.00, "PB": 0.00, "Ticker": "5AE", "Sector": "Real Estate"},
    "Prime US ReitUSD": {"Rate": 0.00, "PB": 0.00, "Ticker": "OXMU", "Sector": "Real Estate"},
    "PropNex": {"Rate": 0.00, "PB": 0.00, "Ticker": "OYY", "Sector": "Real Estate"},
    "Regal Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "UV1", "Sector": "Real Estate"},
    "Sasseur Reit": {"Rate": 0.00, "PB": 0.00, "Ticker": "CRPU", "Sector": "REITs & Business Trusts"},
    "SingHoldings": {"Rate": 0.00, "PB": 0.00, "Ticker": "5IC", "Sector": "Real Estate"},
    "SingaporeLandGrp": {"Rate": 0.00, "PB": 0.00, "Ticker": "U06", "Sector": "Real Estate"},
    "Soon Hock": {"Rate": 0.00, "PB": 0.00, "Ticker": "SHE", "Sector": "Real Estate"},
    "StarhillGbl Reit": {"Rate": 0.04, "PB": 0.72, "Ticker": "P40U", "Sector": "REITs & Business Trusts"},
    "Stoneweg EUTrust EUR": {"Rate": 0.00, "PB": 0.00, "Ticker": "SET", "Sector": "REITs & Business Trusts"},
    "Stoneweg EUTrust SGD": {"Rate": 0.00, "PB": 0.00, "Ticker": "SEB", "Sector": "REITs & Business Trusts"},
    "Sunrise Shares": {"Rate": 0.00, "PB": 0.00, "Ticker": "581", "Sector": "Real Estate"},
    "Suntec Reit": {"Rate": 0.08, "PB": 0.62, "Ticker": "T82U", "Sector": "REITs & Business Trusts"},
    "TAP": {"Rate": 0.00, "PB": 0.00, "Ticker": "TAP", "Sector": "Real Estate"},
    "Tosei": {"Rate": 0.00, "PB": 0.00, "Ticker": "S2D", "Sector": "Real Estate"},
    "Tuan Sing": {"Rate": 0.00, "PB": 0.00, "Ticker": "T24", "Sector": "Real Estate"},
    "UIBREIT": {"Rate": 0.00, "PB": 0.00, "Ticker": "UIBU", "Sector": "REITs & Business Trusts"},
    "UOA": {"Rate": 0.00, "PB": 0.00, "Ticker": "EH5", "Sector": "Real Estate"},
    "UOL": {"Rate": 0.02, "PB": 0.45, "Ticker": "U14", "Sector": "Real Estate"},
    "UtdHampshReitUSD": {"Rate": 0.00, "PB": 0.00, "Ticker": "ODBU", "Sector": "Real Estate"},
    "Wing Tai": {"Rate": 0.00, "PB": 0.00, "Ticker": "W05", "Sector": "Real Estate"},
    "Yamada Green Res": {"Rate": 0.00, "PB": 0.00, "Ticker": "BJV", "Sector": "Real Estate"},
    "Yanlord Land": {"Rate": 0.00, "PB": 0.00, "Ticker": "Z25", "Sector": "Real Estate"},
    "Ying Li Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "5DM", "Sector": "Real Estate"},
    "17LIVE GROUP": {"Rate": 0.00, "PB": 0.00, "Ticker": "LVR", "Sector": "Technology"},
    "8Telecom": {"Rate": 0.00, "PB": 0.00, "Ticker": "AZG", "Sector": "Technology"},
    "9R": {"Rate": 0.00, "PB": 0.00, "Ticker": "1Y1", "Sector": "Technology"},
    "AEM SGD": {"Rate": 0.00, "PB": 0.00, "Ticker": "AWX", "Sector": "Technology"},
    "AEM USD": {"Rate": 0.00, "PB": 0.00, "Ticker": "XWA", "Sector": "Technology"},
    "ASTI": {"Rate": 0.00, "PB": 0.00, "Ticker": "575", "Sector": "Technology"},
    "Addvalue Tech": {"Rate": 0.00, "PB": 0.00, "Ticker": "A31", "Sector": "Technology"},
    "AdvancedSystems": {"Rate": 0.00, "PB": 0.00, "Ticker": "WJ9", "Sector": "Technology"},
    "AlphaDX": {"Rate": 0.00, "PB": 0.00, "Ticker": "VVL", "Sector": "Technology"},
    "Assurance HC": {"Rate": 0.00, "PB": 0.00, "Ticker": "RCU", "Sector": "Technology"},
    "AvePoint": {"Rate": 0.00, "PB": 0.00, "Ticker": "AVP", "Sector": "Technology"},
    "Avi-Tech Hldg": {"Rate": 0.00, "PB": 0.00, "Ticker": "1R6", "Sector": "Technology"},
    "Azeus": {"Rate": 0.00, "PB": 0.00, "Ticker": "BBW", "Sector": "Technology"},
    "Aztech Gbl": {"Rate": 0.00, "PB": 0.00, "Ticker": "8AZ", "Sector": "Technology"},
    "Broadway Ind": {"Rate": 0.00, "PB": 0.00, "Ticker": "B69", "Sector": "Technology"},
    "CDW": {"Rate": 0.00, "PB": 0.00, "Ticker": "BXE", "Sector": "Technology"},
    "CSE Global": {"Rate": 0.00, "PB": 0.00, "Ticker": "544", "Sector": "Technology"},
    "Choo Chiang": {"Rate": 0.00, "PB": 0.00, "Ticker": "42E", "Sector": "Technology"},
    "Comba": {"Rate": 0.00, "PB": 0.00, "Ticker": "STC", "Sector": "Technology"},
    "Creative": {"Rate": 0.00, "PB": 0.00, "Ticker": "C76", "Sector": "Technology"},
    "DISA": {"Rate": 0.00, "PB": 0.00, "Ticker": "532", "Sector": "Technology"},
    "Ellipsiz": {"Rate": 0.00, "PB": 0.00, "Ticker": "BIX", "Sector": "Technology"},
    "Frencken": {"Rate": 0.00, "PB": 0.00, "Ticker": "E28", "Sector": "Technology"},
    "G Invacom": {"Rate": 0.00, "PB": 0.00, "Ticker": "QS9", "Sector": "Technology"},
    "GRP": {"Rate": 0.00, "PB": 0.00, "Ticker": "BLU", "Sector": "Technology"},
    "GSS Energy": {"Rate": 0.00, "PB": 0.00, "Ticker": "41F", "Sector": "Technology"},
    "Global Testing": {"Rate": 0.00, "PB": 0.00, "Ticker": "AYN", "Sector": "Technology"},
    "IFAST": {"Rate": 0.00, "PB": 0.00, "Ticker": "AIY", "Sector": "Technology"},
    "Info-Tech": {"Rate": 0.00, "PB": 0.00, "Ticker": "ITS", "Sector": "Technology"},
    "Jadason": {"Rate": 0.00, "PB": 0.00, "Ticker": "J03", "Sector": "Technology"},
    "Jason Marine": {"Rate": 0.00, "PB": 0.00, "Ticker": "5PF", "Sector": "Technology"},
    "Jubilee": {"Rate": 0.00, "PB": 0.00, "Ticker": "NHD", "Sector": "Technology"},
    "Karin Tech": {"Rate": 0.00, "PB": 0.00, "Ticker": "K29", "Sector": "Technology"},
    "MDR Limited": {"Rate": 0.00, "PB": 0.00, "Ticker": "Y3D", "Sector": "Technology"},
    "METAOPTICS LTD": {"Rate": 0.00, "PB": 0.00, "Ticker": "9MT", "Sector": "Technology"},
    "MFG Integration": {"Rate": 0.00, "PB": 0.00, "Ticker": "M11", "Sector": "Technology"},
    "Maruwa Yen1k": {"Rate": 0.00, "PB": 0.00, "Ticker": "M12", "Sector": "Technology"},
    "Micro-Mechanics": {"Rate": 0.00, "PB": 0.00, "Ticker": "5DD", "Sector": "Technology"},
    "Multi-Chem": {"Rate": 0.00, "PB": 0.00, "Ticker": "AWZ", "Sector": "Technology"},
    "Nanofilm": {"Rate": 0.00, "PB": 0.00, "Ticker": "MZH", "Sector": "Technology"},
    "NeraTel": {"Rate": 0.00, "PB": 0.00, "Ticker": "N01", "Sector": "Technology"},
    "OIO": {"Rate": 0.00, "PB": 0.00, "Ticker": "KUX", "Sector": "Technology"},
    "OxPay Financial": {"Rate": 0.00, "PB": 0.00, "Ticker": "TVV", "Sector": "Technology"},
    "PC Partner": {"Rate": 0.00, "PB": 0.00, "Ticker": "PCT", "Sector": "Technology"},
    "PNE Industries": {"Rate": 0.00, "PB": 0.00, "Ticker": "BDA", "Sector": "Technology"},
    "Powermatic Data": {"Rate": 0.00, "PB": 0.00, "Ticker": "BCY", "Sector": "Technology"},
    "Santak": {"Rate": 0.00, "PB": 0.00, "Ticker": "580", "Sector": "Technology"},
    "Sarine Tech": {"Rate": 0.00, "PB": 0.00, "Ticker": "U77", "Sector": "Technology"},
    "Serial Achieva": {"Rate": 0.00, "PB": 0.00, "Ticker": "XHV", "Sector": "Technology"},
    "Serial System": {"Rate": 0.00, "PB": 0.00, "Ticker": "S69", "Sector": "Technology"},
    "SinoCloud Grp": {"Rate": 0.00, "PB": 0.00, "Ticker": "LYY", "Sector": "Technology"},
    "Sunright": {"Rate": 0.00, "PB": 0.00, "Ticker": "S71", "Sector": "Technology"},
    "Toku Ltd": {"Rate": 0.00, "PB": 0.00, "Ticker": "TKU", "Sector": "Technology"},
    "Totm Tech": {"Rate": 0.00, "PB": 0.00, "Ticker": "42F", "Sector": "Technology"},
    "Trek 2000 Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "5AB", "Sector": "Technology"},
    "TrickleStar": {"Rate": 0.00, "PB": 0.00, "Ticker": "CYW", "Sector": "Technology"},
    "UMS": {"Rate": 0.00, "PB": 0.00, "Ticker": "558", "Sector": "Technology"},
    "Valuetronics": {"Rate": 0.00, "PB": 0.00, "Ticker": "BN2", "Sector": "Technology"},
    "Venture": {"Rate": 0.75, "PB": 1.22, "Ticker": "V03", "Sector": "Technology"},
    "Willas-Array": {"Rate": 0.00, "PB": 0.00, "Ticker": "BDR", "Sector": "Technology"},
    "Yunnan Energy": {"Rate": 0.00, "PB": 0.00, "Ticker": "T43", "Sector": "Technology"},
    "iWOW Tech": {"Rate": 0.00, "PB": 0.00, "Ticker": "NXR", "Sector": "Technology"},
    "Asiatic": {"Rate": 0.00, "PB": 0.00, "Ticker": "5CR", "Sector": "Utilities"},
    "CONCORD NE": {"Rate": 0.00, "PB": 0.00, "Ticker": "SEG", "Sector": "Utilities"},
    "China Everbright": {"Rate": 0.00, "PB": 0.00, "Ticker": "U9E", "Sector": "Utilities"},
    "China Intl": {"Rate": 0.00, "PB": 0.00, "Ticker": "BEH", "Sector": "Utilities"},
    "Gallant Venture": {"Rate": 0.00, "PB": 0.00, "Ticker": "5IG", "Sector": "Utilities"},
    "Hyflux": {"Rate": 0.00, "PB": 0.00, "Ticker": "600", "Sector": "Utilities"},
    "Khen Energy": {"Rate": 0.00, "PB": 0.00, "Ticker": "YSV", "Sector": "Utilities"},
    "Memiontec Hldgs": {"Rate": 0.00, "PB": 0.00, "Ticker": "TWL", "Sector": "Utilities"},
    "Metis Energy": {"Rate": 0.00, "PB": 0.00, "Ticker": "L02", "Sector": "Utilities"},
    "Ouhua Energy": {"Rate": 0.00, "PB": 0.00, "Ticker": "AJ2", "Sector": "Utilities"},
    "Renaissance United": {"Rate": 0.00, "PB": 0.00, "Ticker": "I11", "Sector": "Utilities"},
    "SIIC Environment": {"Rate": 0.00, "PB": 0.00, "Ticker": "BHK", "Sector": "Utilities"},
    "Sembcorp Ind": {"Rate": 0.15, "PB": 1.42, "Ticker": "U96", "Sector": "Utilities"},
    "Sunpower": {"Rate": 0.00, "PB": 0.00, "Ticker": "5GD", "Sector": "Utilities"},
    "Zheneng Jinjiang": {"Rate": 0.00, "PB": 0.00, "Ticker": "BWM", "Sector": "Utilities"},
    "ASTREAVIB310318": {"Rate": 0.03, "PB": 1.00, "Ticker": None, "Sector": "Fixed Income"},
    "ASTREA7A1320527": {"Rate": 0.041, "PB": 1.00, "Ticker": "V7AB", "Sector": "Fixed Income"},
    "ASTREA7B320527": {"Rate": 0.06, "PB": 1.00, "Ticker": "V7BB", "Sector": "Fixed Income"},
    "ASTREA8A1390719": {"Rate": 0.0435, "PB": 1.00, "Ticker": "Z1AB", "Sector": "Fixed Income"},
    "ASTREA8A2390719": {"Rate": 0.0435, "PB": 1.00, "Ticker": "Z2AB", "Sector": "Fixed Income"},
    "ASTREA9A1400808": {"Rate": 0.034, "PB": 1.00, "Ticker": "YA1B", "Sector": "Fixed Income"},
    "ASTREA9A2400808": {"Rate": 0.057, "PB": 1.00, "Ticker": "YA2B", "Sector": "Fixed Income"},
    "CITYDEV NCCPS": {"Rate": 0.039, "PB": 1.00, "Ticker": "C70", "Sector": "Fixed Income"},
    "SBDEC17 GX17120W": {"Rate": 0.0216, "PB": 1.00, "Ticker": None, "Sector": "Fixed Income"},
}
